apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-app
  labels:
    app: devops-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-app
  template:
    metadata:
      labels:
        app: devops-app
    spec:
      containers:
        - name: devops-container
          image: 071785598364.dkr.ecr.us-east-1.amazonaws.com/devops-node-app:latest
          ports:
            - containerPort: 8080
